### PR TITLE
[BZ-1257907] add brms-bpmsuite-platform-bom

### PR DESCRIPTION
**Pull request by psiroky**
@ryanzhang @winklerm please just double check if I did not miss something

### CODE REVIEW

**Comment by psiroky** [comment]
This should be only merged into 6.1.x branch. 6.2.x already contains platform BOM.

**Comment by psiroky** [comment]
Added import of `jboss-brms-bpmsuite-bom` to make it clear that the platform BOM is superset of that user BOM. 

Added README.

@pkocandr thanks for comments!

**Comment by winklerm** [comment]
Looks good to me!

**Comment by ryanzhang** [comment]
+1 
(Sorry, I haven't seen this before)

**Pull request merged**
